[package]
name = "docfinder"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
reqwest = {version = "0.11.18", features = ["blocking"]}
scraper = "0.16"
serde = { version = "1.0", features = ["derive"] }
